# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VoloReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VoloReactNative

  # target 'VoloReactNative-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'VoloReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'VoloReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VoloReactNative-tvOS

  target 'VoloReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
